import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
export async function runAdminBrowser({origin,admin,users,group,request,check}){
 const require=createRequire(import.meta.url);const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
 const browser=await chromium.launch({headless:true,...(process.env.LETCHAT_CHROMIUM_PATH?{executablePath:process.env.LETCHAT_CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--use-gl=angle','--use-angle=swiftshader']});
 const output=process.env.LETCHAT_QA_OUTPUT||'/tmp/letchat-admin-qa';await mkdir(output,{recursive:true});const errors=[];
 const firebase=`export const initializeApp=()=>({});export const getAuth=()=>({currentUser:null});export class GoogleAuthProvider{setCustomParameters(){}};export const browserLocalPersistence={};export const setPersistence=async()=>{};export const getRedirectResult=async()=>null;export const onAuthStateChanged=(a,cb)=>{setTimeout(()=>cb(null),0);return()=>{}};export const signInWithPopup=async()=>{};export const signInWithRedirect=async()=>{};export const signOut=async()=>{};export const deleteUser=async()=>{};`;
 async function pageFor(person,viewport){const ctx=await browser.newContext({viewport,serviceWorkers:'block'});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.route('https://www.gstatic.com/firebasejs/**',r=>r.fulfill({status:200,contentType:'text/javascript',body:firebase}));await p.addInitScript(token=>{localStorage.setItem('letchatLocalToken',token);localStorage.setItem('letchat-theme','light');},person.token);await p.goto(origin,{waitUntil:'networkidle'});await p.locator('#communityHome[open] [data-close]').click();await p.locator('#meName').filter({hasText:person.user.name}).waitFor();if(await p.locator('#profileModal').isVisible())await p.locator('#closeProfile').click();return p;}
 try{
  const ordinary=await pageFor(users[1],{width:1280,height:900});
  const p=await pageFor(admin,{width:1440,height:1000});await p.locator(`.person-button[data-user-id="${users[1].user.id}"]`).first().click();await p.locator('#adminBtn').click();await p.locator('.adm-stats article').first().waitFor();
  check(await p.locator('#adminModal').evaluate(d=>d.open)&&await p.locator('#adminModal').isVisible(),'admin opens visibly after visiting a private conversation');
  await p.screenshot({path:output+'/administration-bureau.png'});
  for(const tab of ['reports','members','rooms','groups','subscriptions','journal','system']){await p.locator(`[data-tab="${tab}"]`).click();await p.waitForFunction(()=>!document.querySelector('.adm-content').hasAttribute('aria-busy'));assert.equal(await p.locator('.adm-error').isVisible(),false,tab+' should load');}
  check(true,'all eight admin sections render with live fixture API');
  await p.locator('[data-tab="members"]').click();await p.locator('.adm-filters input[name=q]').fill('Bob test');await p.locator('.adm-filter-form [type=submit]').click();await p.locator('.adm-content [data-do=member]').first().click();await p.locator('.adm-subdialog [data-do=note]').waitFor();
  await p.locator('.adm-subdialog [data-do=note]').click();await p.locator('.adm-subdialog textarea').fill('Note de suivi saisie depuis le navigateur');await p.locator('.adm-subdialog button[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('.adm-subdialog').open);
  const detail=(await request(`/api/admin/profiles/${users[1].user.id}`,admin.token)).json;check(detail.history.some(h=>h.details==='Note de suivi saisie depuis le navigateur'),'member note saves through actual UI');
  await p.locator('[data-tab="rooms"]').click();await p.locator('[data-do=room-settings][data-id=cafe]').click();await p.locator('.adm-subdialog select[name=readOnly]').selectOption('true');await p.locator('.adm-subdialog textarea[name=notice]').fill('Salon temporairement en lecture seule');await p.locator('.adm-subdialog textarea[name=reason]').fill('Vérification visuelle de la modération');await p.locator('.adm-subdialog button[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('.adm-subdialog').open);
  check((await request('/api/admin/rooms',admin.token)).json.find(r=>r.id==='cafe').read_only,'room form updates live server settings');
  await p.locator('[data-do=room-settings][data-id=cafe]').click();await p.locator('.adm-subdialog select[name=readOnly]').selectOption('false');await p.locator('.adm-subdialog textarea[name=notice]').fill('');await p.locator('.adm-subdialog textarea[name=reason]').fill('Fin de vérification');await p.locator('.adm-subdialog button[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('.adm-subdialog').open);
  await p.locator('[data-tab=reports]').click();await p.locator('select[name=status]').selectOption('all');await p.locator('.adm-filter-form [type=submit]').click();await p.locator('.adm-report').first().waitFor();await p.screenshot({path:output+'/administration-signalements.png'});
  await p.locator('[data-do=report-media]').first().click();await p.waitForFunction(()=>document.querySelector('.adm-evidence-media')?.naturalWidth>0);check(true,'reported image is displayed in authenticated review dialog');await p.locator('.adm-subdialog [data-sub-close]').click();
  await p.locator('[data-do=report-edit]').first().click();await p.locator('.adm-subdialog select[name=status]').selectOption('dismissed');await p.locator('.adm-subdialog textarea[name=note]').fill('Décision saisie lors du parcours navigateur');await p.locator('.adm-subdialog button[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('.adm-subdialog').open);check(true,'report decision can be submitted with an internal note');
  await p.locator('[data-tab=members]').click();await p.waitForFunction(()=>!document.querySelector('.adm-content').hasAttribute('aria-busy'));await p.locator('[data-do=next]').click();await p.locator('.adm-footer').filter({hasText:'Page 2'}).waitFor();check(true,'pagination works in the browser');
  await p.locator('.adm-filters input[name=q]').fill('<img');await p.locator('.adm-filter-form [type=submit]').click();await p.locator('.adm-content').getByText('<img src=x onerror=alert(1)>',{exact:true}).waitFor();check(await p.locator('.adm-content img').count()===0,'member content is escaped against stored HTML injection');
  await p.keyboard.press('Escape');check(!await p.locator('#adminModal').evaluate(d=>d.open),'Escape closes administration');
  check(await ordinary.locator('#adminBtn').isHidden(),'ordinary member has no admin entry point');
  await ordinary.locator('[data-groups]').click();await ordinary.locator(`[data-group="${group.id}"]`).click();await ordinary.locator('[data-report-message]').first().click();await ordinary.locator('#reportModal').waitFor({state:'visible'});await ordinary.locator('#reportReason').selectOption('spam');await ordinary.locator('#reportDetails').fill('Signalé depuis la conversation de groupe');await ordinary.locator('#reportForm [type=submit]').click();await ordinary.locator('#reportModal').waitFor({state:'hidden'});
  check((await request('/api/admin/reports?kind=group',admin.token)).json.items.some(r=>r.details==='Signalé depuis la conversation de groupe'),'group report button opens form and submits real evidence');
  const mobile=await pageFor(admin,{width:390,height:844});await mobile.locator('#mobileNavMore').click();await mobile.locator('[data-mobile-action=adminBtn]').click();await mobile.locator('.adm-stats article').first().waitFor();await mobile.screenshot({path:output+'/administration-mobile.png'});
  check(await mobile.locator('.adm-main').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'mobile overview fits its viewport');
  await mobile.evaluate(()=>document.documentElement.dataset.theme='dark');await mobile.locator('[data-tab=members]').click();await mobile.waitForFunction(()=>!document.querySelector('.adm-content').hasAttribute('aria-busy'));await mobile.screenshot({path:output+'/administration-mobile-sombre.png'});
  check(await mobile.locator('.adm-main').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'mobile dark member view has no page overflow');
  await mobile.locator('.adm-content [data-do=member]').first().click();await mobile.locator('.adm-subdialog .adm-details').waitFor();check(await mobile.locator('.adm-subdialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'member dialog fits mobile width');
  await mobile.keyboard.press('Escape');check(await mobile.locator('#adminModal').evaluate(d=>d.open),'closing member detail keeps administration open');
  await mobile.locator('[data-tab=reports]').click();await mobile.locator('.adm-report').first().waitFor();await mobile.screenshot({path:output+'/administration-mobile-signalements.png'});
  check(errors.length===0,'no browser JavaScript errors: '+errors.join('; '));
 }finally{await browser.close();}
}
