import { createRequire } from "node:module";
import { mkdir } from "node:fs/promises";

export async function runCommunityBrowserQA({origin,users,request,check}) {
  const require=createRequire(import.meta.url);
  const {chromium}=require(require.resolve("playwright",{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
  const custom=process.env.LETCHAT_CHROMIUM_MODULE ? (await import(process.env.LETCHAT_CHROMIUM_MODULE)).default : null;
  const browser=await chromium.launch({headless:true,...(custom?{executablePath:await custom.executablePath()}:{}),args:[...(custom?.args||[]).filter(a=>!["--single-process","--disable-web-security","--allow-running-insecure-content"].includes(a)),"--no-sandbox"]});
  const output=process.env.LETCHAT_QA_OUTPUT||"/tmp/letchat-community-qa",errors=[];
  await mkdir(output,{recursive:true});
  const firebase=`export const initializeApp=()=>({});export const getAuth=()=>({currentUser:null});export class GoogleAuthProvider {setCustomParameters(){}};export const browserLocalPersistence={};export const setPersistence=async()=>{};export const getRedirectResult=async()=>null;export const onAuthStateChanged=(a,cb)=>{setTimeout(()=>cb(null),0);return ()=>{}};export const signInWithPopup=async()=>{};export const signInWithRedirect=async()=>{};export const signOut=async()=>{};export const deleteUser=async()=>{};`;
  try {
    const pages=[];
    for(let i=0;i<2;i++) {
      const context=await browser.newContext({viewport:i?{width:390,height:844}:{width:1365,height:940},serviceWorkers:"block"});
      const page=await context.newPage();page.setDefaultTimeout(12000);pages.push(page);
      page.on('pageerror',error=>errors.push(error.message));
      await page.route("https://www.gstatic.com/firebasejs/**",route=>route.fulfill({status:200,contentType:"text/javascript",body:firebase}));
      await page.route(/googlesyndication|doubleclick|google-analytics/,route=>route.abort());
      await page.addInitScript(({token,guest,theme})=>{(guest?sessionStorage:localStorage).setItem(guest?"letchatGuestToken":"letchatLocalToken",token);localStorage.setItem("letchat-theme",theme);},{token:users[i].token,guest:users[i].user.guest,theme:i?"dark":"light"});
      await page.goto(origin,{waitUntil:"networkidle"});
      await page.waitForFunction(()=>document.querySelector('#connectionStatus')?.dataset.state==='online');
      await page.locator('#communityHome[open]').waitFor();
      await page.locator('[data-community-room="cafe"]').waitFor();
      check(await page.locator('#communityHome').evaluate(e=>e.scrollWidth<=e.clientWidth+1),`home fits ${i?'mobile dark':'desktop light'} viewport`);
    }
    const [desktop,mobile]=pages;
    await desktop.screenshot({path:output+'/accueil-ordinateur.png'});
    await mobile.screenshot({path:output+'/accueil-mobile-sombre.png'});
    await desktop.locator('[data-community-room="cafe"]').click();
    await mobile.locator('[data-community-room="cafe"]').click();
    check(await mobile.locator('.community-mobile-nav button').count()===4,'mobile bottom navigation exposes all four destinations');
    const before=await request('/api/private',users[0].token,'POST',{recipientId:users[1].user.id,body:'Un message à conserver avec le profil'});
    check(before.status===201,'test recipient has a conversation before guest conversion');
    await mobile.locator('.community-unread:not([hidden])').waitFor();
    check(await mobile.locator('[data-destination="messages"]').getAttribute('aria-label')==='Messages, 1 non lus','mobile unread badge is synchronized and accessible');
    await mobile.locator('[data-destination="members"]').click();
    await mobile.locator('#onlineMembersModal:not(.hidden)').waitFor();
    await mobile.locator('#closeOnlineMembers').click();
    await mobile.locator('[data-destination="profile"]').click();
    await mobile.locator('.profile-guest-upgrade button').click();
    await mobile.locator('#guestUpgrade input[name=username]').fill('Invite Browser permanent');
    await mobile.locator('#guestUpgrade input[name=password]').fill('Browser-Permanent-1234');
    await mobile.locator('#guestUpgrade input[name=confirmation]').fill('Not-identical-1234');
    await mobile.locator('#guestUpgrade [type=submit]').click();
    check((await mobile.locator('#guestUpgrade .community-error').textContent()).includes('identiques'),'confirmation mismatch is explained in the form');
    await mobile.locator('#guestUpgrade input[name=confirmation]').fill('Browser-Permanent-1234');
    await mobile.screenshot({path:output+'/conserver-compte-mobile.png'});
    await mobile.locator('#guestUpgrade [type=submit]').click();
    await mobile.locator('#recoveryCodeDialog[open]').waitFor();
    check(await mobile.locator('.guest-reminder').isHidden(),'conversion removes the temporary-account reminder');
    await mobile.locator('#closeRecoveryCode').click();
    await mobile.waitForFunction(()=>document.querySelector('#connectionStatus')?.dataset.state==='online');
    await mobile.locator('[data-destination="messages"]').click();
    await mobile.getByText('Un message à conserver avec le profil',{exact:true}).first().waitFor();
    check(true,'converted guest sees the earlier private conversation');
    await mobile.locator('[data-destination="rooms"]').click();
    await mobile.locator('#communityHome [data-surprise]').click();
    await mobile.locator('[data-interest="cinema"]').click();
    await mobile.locator('.surprise-dialog [data-start]').click();
    await mobile.locator('.surprise-alternative:not([hidden])').waitFor();
    check((await mobile.locator('.surprise-elapsed').textContent()).includes('Attente'),'waiting screen shows elapsed time');
    await mobile.screenshot({path:output+'/surprise-mobile-sombre.png'});
    await desktop.locator('#surpriseLink').click();
    await desktop.locator('[data-interest="cinema"]').click();
    await desktop.locator('.surprise-dialog [data-start]').click();
    await mobile.locator('.surprise-dialog').waitFor({state:'hidden'});
    await desktop.locator('.surprise-dialog').waitFor({state:'hidden'});
    await desktop.locator('#input').fill('Bonjour, parlons cinéma !');await desktop.locator('#send').click();
    await mobile.locator('#messages').getByText('Bonjour, parlons cinéma !',{exact:true}).waitFor();
    check(true,'matching by interest opens a working conversation on both devices');
    await mobile.locator('#messageToast').waitFor({state:'hidden'});
    await mobile.screenshot({path:output+'/conversation-mobile-sombre.png',timeout:5000});
    await mobile.locator('#input').focus();
    await mobile.setViewportSize({width:390,height:500});
    await mobile.waitForFunction(()=>document.body.classList.contains('mobile-keyboard-open'));
    const input=await mobile.locator('#input').boundingBox();
    check(input.y>=0&&input.y+input.height<=500&&await mobile.locator('.community-mobile-nav').isHidden(),'reduced viewport keeps the composer visible and hides navigation while typing');
    await mobile.locator('#input').blur();await mobile.setViewportSize({width:390,height:844});
    await mobile.locator('.surprise-bar [data-leave]').click();
    await mobile.locator('[data-destination="rooms"]').click();await mobile.locator('#communityHome [data-surprise]').click();
    await mobile.locator('.surprise-dialog [data-start]').click();
    await mobile.locator('[data-browse]').click();
    await mobile.locator('#communityHome[open]').waitFor();
    check(await mobile.locator('.surprise-bar').isHidden(),'salon fallback cancels matching before opening home');
    await mobile.evaluate(()=>document.documentElement.dataset.theme='light');
    await mobile.setViewportSize({width:320,height:640});
    check(await mobile.locator('#communityHome').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'home remains readable at 320 pixels');
    check(errors.length===0,'no browser JavaScript errors: '+errors.join('; '));
    await mobile.screenshot({path:output+'/accueil-mobile-clair-320.png',timeout:5000});
    console.log('Browser screenshots: '+output);
  } finally { await browser.close(); }
}
