const express=require('express');const http=require('http');const path=require('path');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const {Pool}=require('pg');const {Server}=require('socket.io');
const PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'change-me';if(!process.env.DATABASE_URL){console.error('DATABASE_URL is required');process.exit(1)}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}});const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
const q=(s,p=[])=>pool.query(s,p);
async function init(){await q(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username VARCHAR(30) UNIQUE NOT NULL,password_hash TEXT NOT NULL,avatar VARCHAR(20) DEFAULT '🙂',status VARCHAR(120) DEFAULT 'En ligne',bio VARCHAR(500) DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW())`);for(const s of [`ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar VARCHAR(20) DEFAULT '🙂'`,`ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(120) DEFAULT 'En ligne'`,`ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(500) DEFAULT ''`])await q(s);await q(`CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,text TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())`);await q(`CREATE TABLE IF NOT EXISTS private_messages(id BIGSERIAL PRIMARY KEY,sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,text TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())`);await q(`CREATE TABLE IF NOT EXISTS friendships(id BIGSERIAL PRIMARY KEY,sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,status VARCHAR(20) NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(sender_id,receiver_id))`)}
async function user(id){const r=await q('SELECT id,username,avatar,status,bio,created_at FROM users WHERE id=$1',[id]);return r.rows[0]||null}function pub(u,on=false){return{id:u.id,username:u.username,avatar:u.avatar||'🙂',status:u.status||'En ligne',bio:u.bio||'',createdAt:u.created_at,online:on}}function token(u){return jwt.sign({id:u.id},JWT_SECRET,{expiresIn:'30d'})}
async function auth(req,res,next){try{const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'Non connecté.'});const p=jwt.verify(t,JWT_SECRET),u=await user(p.id);if(!u)return res.status(401).json({error:'Utilisateur introuvable.'});req.user=u;next()}catch(e){res.status(401).json({error:'Session invalide.'})}}
const online=new Map();
app.post('/api/register',async(req,res)=>{try{const username=String(req.body.username||'').trim(),password=String(req.body.password||'');if(!/^[a-zA-Z0-9_]{3,30}$/.test(username))return res.status(400).json({error:'Nom: 3-30 caractères, lettres/chiffres/_. '});if(password.length<6)return res.status(400).json({error:'Mot de passe: 6 caractères minimum.'});if((await q('SELECT id FROM users WHERE LOWER(username)=LOWER($1)',[username])).rowCount)return res.status(409).json({error:'Ce nom existe déjà.'});const h=await bcrypt.hash(password,12),r=await q('INSERT INTO users(username,password_hash) VALUES($1,$2) RETURNING id,username,avatar,status,bio,created_at',[username,h]);res.status(201).json({token:token(r.rows[0]),user:pub(r.rows[0])})}catch(e){console.error(e);res.status(500).json({error:'Erreur inscription.'})}});
app.post('/api/login',async(req,res)=>{try{const username=String(req.body.username||'').trim(),password=String(req.body.password||''),r=await q('SELECT * FROM users WHERE LOWER(username)=LOWER($1)',[username]);if(!r.rowCount)return res.status(401).json({error:'Identifiants incorrects.'});const u=r.rows[0];if(!await bcrypt.compare(password,u.password_hash))return res.status(401).json({error:'Identifiants incorrects.'});res.json({token:token(u),user:pub(u,online.has(String(u.id)))})}catch(e){console.error(e);res.status(500).json({error:'Erreur connexion.'})}});
app.get('/api/me',auth,async(req,res)=>{const u=await user(req.user.id);res.json({user:pub(u,online.has(String(u.id)))})});
app.patch('/api/me',auth,async(req,res)=>{const a=String(req.body.avatar??'🙂').trim().slice(0,20)||'🙂',s=String(req.body.status??'En ligne').trim().slice(0,120)||'En ligne',b=String(req.body.bio??'').trim().slice(0,500),r=await q('UPDATE users SET avatar=$1,status=$2,bio=$3 WHERE id=$4 RETURNING id,username,avatar,status,bio,created_at',[a,s,b,req.user.id]);res.json({user:pub(r.rows[0],online.has(String(req.user.id)))});io.emit('presence')});
app.get('/api/users',auth,async(req,res)=>{const r=await q('SELECT id,username,avatar,status,bio,created_at FROM users ORDER BY LOWER(username)');res.json(r.rows.map(u=>pub(u,online.has(String(u.id))))) });
app.get('/api/messages',auth,async(req,res)=>{const r=await q(`SELECT m.id,m.user_id,m.text,m.created_at,u.username,u.avatar FROM messages m JOIN users u ON u.id=m.user_id ORDER BY m.id ASC LIMIT 300`);res.json(r.rows.map(m=>({id:m.id,userId:m.user_id,username:m.username,avatar:m.avatar,text:m.text,createdAt:m.created_at}))) });
app.get('/api/private/:id',auth,async(req,res)=>{const id=Number(req.params.id),r=await q(`SELECT p.id,p.sender_id,p.receiver_id,p.text,p.created_at,u.username,u.avatar FROM private_messages p JOIN users u ON u.id=p.sender_id WHERE (p.sender_id=$1 AND p.receiver_id=$2) OR (p.sender_id=$2 AND p.receiver_id=$1) ORDER BY p.id ASC LIMIT 300`,[req.user.id,id]);res.json(r.rows.map(m=>({id:m.id,senderId:m.sender_id,toUserId:m.receiver_id,username:m.username,avatar:m.avatar,text:m.text,createdAt:m.created_at}))) });
app.get('/api/friends',auth,async(req,res)=>{const r=await q(`SELECT f.*,u.username,u.avatar,u.status user_status FROM friendships f JOIN users u ON u.id=CASE WHEN f.sender_id=$1 THEN f.receiver_id ELSE f.sender_id END WHERE f.sender_id=$1 OR f.receiver_id=$1 ORDER BY f.id DESC`,[req.user.id]);res.json(r.rows.map(f=>({id:f.id,userId:Number(f.sender_id)===Number(req.user.id)?f.receiver_id:f.sender_id,username:f.username,avatar:f.avatar||'🙂',userStatus:f.user_status||'En ligne',status:f.status,direction:Number(f.sender_id)===Number(req.user.id)?'sent':'received',createdAt:f.created_at}))) });
app.post('/api/friends/:id',auth,async(req,res)=>{try{const id=Number(req.params.id);if(!Number.isInteger(id)||id===Number(req.user.id))return res.status(400).json({error:'Utilisateur invalide.'});if(!await user(id))return res.status(404).json({error:'Utilisateur introuvable.'});const e=await q('SELECT * FROM friendships WHERE (sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1) LIMIT 1',[req.user.id,id]);if(e.rowCount){const f=e.rows[0];if(f.status==='pending'&&Number(f.receiver_id)===Number(req.user.id)){const r=await q("UPDATE friendships SET status='accepted' WHERE id=$1 RETURNING *",[f.id]);io.emit('friends:changed');return res.json({ok:true,status:'accepted',friendship:r.rows[0]})}return res.status(409).json({error:'Une demande ou amitié existe déjà.'})}const r=await q("INSERT INTO friendships(sender_id,receiver_id,status) VALUES($1,$2,'pending') RETURNING *",[req.user.id,id]);io.emit('friends:changed');res.status(201).json({ok:true,status:'pending',friendship:r.rows[0]})}catch(e){console.error(e);res.status(500).json({error:'Impossible d’envoyer la demande.'})}});
app.post('/api/friends/:id/accept',auth,async(req,res)=>{const r=await q("UPDATE friendships SET status='accepted' WHERE sender_id=$1 AND receiver_id=$2 AND status='pending' RETURNING *",[Number(req.params.id),req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Demande introuvable.'});io.emit('friends:changed');res.json({ok:true,friendship:r.rows[0]})});
app.delete('/api/friends/:id',auth,async(req,res)=>{await q('DELETE FROM friendships WHERE (sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)',[req.user.id,Number(req.params.id)]);io.emit('friends:changed');res.json({ok:true})});
io.use(async(s,n)=>{try{const t=s.handshake.auth?.token;if(!t)return n(new Error('Non connecté'));const p=jwt.verify(t,JWT_SECRET),u=await user(p.id);if(!u)return n(new Error('Utilisateur introuvable'));s.user=u;n()}catch(e){n(new Error('Session invalide'))}});
io.on('connection',s=>{const id=String(s.user.id);online.set(id,(online.get(id)||0)+1);io.emit('presence');s.on('message:send',async({text},cb)=>{try{text=String(text||'').trim().slice(0,2000);if(!text)return cb?.({ok:false,error:'Message vide'});const r=await q('INSERT INTO messages(user_id,text) VALUES($1,$2) RETURNING id,user_id,text,created_at',[s.user.id,text]);io.emit('message:new',{id:r.rows[0].id,userId:r.rows[0].user_id,username:s.user.username,avatar:s.user.avatar,text:r.rows[0].text,createdAt:r.rows[0].created_at});cb?.({ok:true})}catch(e){cb?.({ok:false,error:'Erreur'})}});s.on('private:send',async({toUserId,text},cb)=>{try{const id=Number(toUserId);text=String(text||'').trim().slice(0,2000);if(!Number.isInteger(id)||!text)return cb?.({ok:false,error:'Message invalide'});if(!await user(id))return cb?.({ok:false,error:'Utilisateur introuvable'});const r=await q('INSERT INTO private_messages(sender_id,receiver_id,text) VALUES($1,$2,$3) RETURNING *',[s.user.id,id,text]);io.emit('private:new',{id:r.rows[0].id,senderId:r.rows[0].sender_id,toUserId:r.rows[0].receiver_id,username:s.user.username,avatar:s.user.avatar,text:r.rows[0].text,createdAt:r.rows[0].created_at});cb?.({ok:true})}catch(e){cb?.({ok:false,error:'Erreur'})}});s.on('typing',()=>s.broadcast.emit('typing',{username:s.user.username}));s.on('stop-typing',()=>s.broadcast.emit('stop-typing'));s.on('disconnect',()=>{const c=online.get(id)||0;c<=1?online.delete(id):online.set(id,c-1);io.emit('presence')})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));init().then(()=>server.listen(PORT,()=>console.log('Letchat on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
